# Generated by Django 2.1 on 2018-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('autor', models.CharField(max_length=100, verbose_name='autor')),
                ('isbn', models.CharField(max_length=100, verbose_name='isbn')),
                ('urlImagen', models.CharField(max_length=100, verbose_name='urlImg')),
                ('editorial', models.CharField(max_length=100, verbose_name='editorial')),
                ('anioPublicacion', models.CharField(max_length=100, verbose_name='anioPublicacion')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['nombre'],
            },
        ),
    ]
